openapi: 3.0.0
info:
  title: Internal Machine API
  description: Gives information about and lets you fire events for the internals of the hot dog vending machine
  version: 0.1.0

servers:
  - url: http://localhost:3006
    description: local development server

paths:
  /inventory:
    get:
      tags:
        - Inventory
      summary: Get inventory information
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: TODO
